### ISSUE TITLE
How to implement agreement and selected account?

### ISSUE THREAD

**Issue by quietbamboo** [Mobiperf/MobiPerf#11]
Currently, when MobiPerf is first run, user will see an agreement asking to agree or just quit.
If user clicks agree, the current MobiPerf would write something into a file in MobiPerf's sandbox.
Next time, just check this file. This method works for the entire life time of an app, even when the device is rebooted, users don't need to click agree again.

Another way to implement, is to use a static variable and change the values of it.
This way, when the app is killed/forced stopeed or the device is rebooted, users will see the agreement window again.

Which of the above two ways is better for our app?

Similar problem exists for selecting account for checkin, i.e., where the selected account should be stored? File or static variable?

**Comment by haneul** [comment]
I think that the choices should be kept even after rebooted for both of choices. 
You may use sharedpreferences ( http://developer.android.com/reference/android/content/SharedPreferences.html ) to store it. (yes, it uses files to store..)

**Comment by mdwelsh** [comment]
I am not 100% sure of the best way to do this, but I assumed there was a standard way in Android of storing persistent state - e.g., as a preference or in a database - rather than having to touch a file. You might want to Google around to see how this is done by other apps - something like this might do it:
http://blog.donnfelker.com/2011/02/17/android-a-simple-eula-for-your-android-apps/

**Comment by quietbamboo** [comment]
OK, I've finished changing to use SharedPreferences and make the old functions Deprecated.
