### ISSUE TITLE
Anonymous selection doesn't work for the boot up time

### ISSUE THREAD

**Issue by teamwork523** [Mobiperf/MobiPerf#124]
I found a bug when you install a fresh MobiPerf, then the program let you select whether you want anonymous account. I actually clicked on the button, and the background information pumped as "You have selected anonymous account". However, if I went back to check the settings, the anonymous option is not selected.

Best,
Haokun
(Since this is the first time I report a issue, I am a graduate student at University of Michigan working for Morley)

**Comment by huangshu91** [comment]
I overlooked this when I was re-implementing accounts.  The account is internally set correctly but isn't reflected int he preferences.  In the previous version it would just default to anonymous I think.  Haokun, could you just take a look at SpeedometerPreferenceActivity.java and just make a check if it is set and if it isn't, default to anonymous, otherwise have the selected account highlighted.

**Comment by ghost** [comment]
This isn't going to fix the issue.

If I select a real account on the first-run dialog, it still isn't set in the preferences. It shouldn't default to anonymous in this case.

It must be that the first-run dialog is not setting the account correctly internally.

**Comment by huangshu91** [comment]
Sorry, I don't understand what you mean by, "If I select a real account on the first-run dialog, it still isn't set in the preferences. It shouldn't default to anonymous in this case."  

When I say it defaults to anonymous I just mean what the default selection is for the list preference.  After selecting the account in the first-run dialog the account should be persisted, it just isn't shown in the preference activity currently.

**Comment by quietbamboo** [comment]
I'm trying to fix this issue now

**Comment by quietbamboo** [comment]
This bug is fixed. Please review the code here http://speedometer-reviews.appspot.com/41001/
